### PR TITLE
Refactor the FogOfWar feature in YR

### PR DESCRIPTION
**Pull request by secsome**
**Fog in YR looks performance really stupid, let's refactor it.**
~~Assigned to kerb~~

### CODE REVIEW

**Comment by SMxReaver** [comment]
Testing the latest nightly build, and man it's crazy to see this in action in the engine again! There are a few hiccups still, but movement in the right direction I feel.


test1
In Test 1, I've seen some clipping when taller structures are re-hidden by the fog of war. Maybe a height issue with fog?

test2
In Test 2, I've seen some odd shroud reveal, not sure if this is an issue with the original shroud graphic or something the engine isn't handling correctly.

test3
In Test 3, you can now see Ore (might be hard to see initially) and gems through the shroud and fog of war.

**Comment by ayylmaoRotE** [comment]
Latest update: Can select units visible under FoW and can also see all units, buildings no longer appear

image

Can also see producecash amounts
image

And lastly not sure if this is simply a fog issue or renderer issue?
image

**Comment by Metadorius** [comment]
Not sure if `ProduceCash` flying strings are fixable since those are Ares stuff.

**Comment by Lylaktech** [comment]
1.Visual Glitches


2.Ore disappears yet the glitter appears through the FoW


3.Ore disappears sometimes even when the area it is in is revealed!


4.Ore drills, which are something that never leaves its' place or die disappear, as well as oil derricks losing their animation part

**Comment by Bu7loos** [comment]
image

I found these problems of the fog of war logic:

1- The AI building there base under the fog of war can be seen.
2- The build up animation can also be seen under the fog of war.
3- The Tesla reactor has a lighting effect attached to it which can be also seen under the fog of war, which basically means any attached light with any structure being built can be spotted.

**Comment by SMxReaver** [comment]
bugtest2
Just want to re-report this issue on the GitHub PR, the commit 1212df0 does not hide laser or line trails, and suffers issues with showing building activeanims through fog on occasion and bibs not appearing under fog.

**Comment by MikillRosen** [comment]
(Mod is my version of D-Day called "D-Day Multiplayer Mod")

Buildings with custom palettes use the unit palette under fog. You can also see other bugs like some buildings being displayed over trees.
DDpal

Destroyed buildings with rubble don't disappear under fog and their rubble (marked by red) remains under it. If you explore it, the building will disappear.
DDrub

There's also a visual bug when going through fog but that's reported a few times here.

**Comment by CatTanker** [comment]
Testing in RotE Beta:

Some buildings appear to have missing parts such as activeanims, as well as missing turrets
Smudges and craters appear behind buildings in certain cases depending on how much is revealed
https://media.discordapp.net/attachments/773636942775582720/876854193305030656/unknown.png

If you select an engineer and hover over some (not all buildings) an icon will appear which shows the building cannot be repaired (such as if it has full HP), however in other locations of the building image the cursor does not change.
(gif coming soon)

Some bugs also appear where an area is suddenly re-shrouded and revealed, especially with the use of support powers. 
this causes some graphical bugs as well due to the area being shrouded yet revealed
https://media.discordapp.net/attachments/773636942775582720/876856330512642099/unknown.png

lasertrails (such as on these aircraft) are also shown through the shroud. this is not an issue normally but for support powers and airdrops there is a bug because the unit does not reveal
In addition, there is an example of an area suddenly being revealed incorrectly
https://cdn.discordapp.com/attachments/773636942775582720/876859005937516585/GIF_16-08-2021_17-02-03.gif

**Comment by MikillRosen** [comment]
(Mod is my version of D-Day called "D-Day Multiplayer Mod")

This building in particular has strange behavior with Fog of War. The building uses an incorrect palette under fog like all buildings with custom palettes, but when you approach it, it becomes invisible.
DD1
Its collision is still there, but it can only be selected on where my cursor is. Trying to select the building outside where my is cursor won't work.
DD2
Why is it behaving this way? It has something to do with its foundation. Copying a different foundation from another building fixes the issue.
DD3
This is the building's original foundation in ArtMD.ini. (Requires Ares to work.)
```
Foundation = Custom
Foundation.X = 5
Foundation.Y = 5
Foundation.0 = 3,0
Foundation.1 = 4,0
Foundation.2 = 3,1
Foundation.3 = 4,1
Foundation.4 = 3,2
Foundation.5 = 4,2
Foundation.6 = 0,3
Foundation.7 = 1,3
Foundation.8 = 2,3
Foundation.9 = 3,3
Foundation.10 = 4,3
Foundation.11 = 0,4
Foundation.12 = 1,4
Foundation.13 = 2,4
Foundation.14 = 3,4
Foundation.15 = 4,4
```

**Comment by secsome** [comment]
Gonna open a new PR instead of keep working on this PR

**Pull request closed without merging**
