### PR TITLE
Making things tidy

### PR DESCRIPTION
**Pull request by secsome**
using the templates from Ares can make our codes tidy.
And further work can be easier with them.

I haven't tested it quite a lot, but few of them has been changed. 
e.g. UIDescription now reads csflabel only.

If you find anys bugs, contact me.

### CODE REVIEW

**Comment by secsome** [comment]
Several tests need to be done before deciding to merge it.

**Comment by Metadorius** [comment]
Wow, that's quite an amount of work! We appreciate that, was planning to refactor the code later but you beat us to it :stuck_out_tongue: We're a bit short on the time at the moment but we'll review and test the stuff soon.

**Comment by secsome** [comment]
#70 and CommandClass_Register are also included in this PR

**Comment by secsome** [comment]
I have commited a encoding fix on YRPP,that's why the build fails.

**Comment by Metadorius** [comment]
> I have commited a encoding fix on YRPP,that's why the build fails.

Could you PR it?

**Comment by secsome** [comment]
Actually I have made a PR to that repository @Metadorius

**Comment by secsome** [comment]
Now it can pass through the checks successfully.

**Comment by Metadorius** [comment]
@secsome Are you on our Discord? I'd like to discuss a few things in real-time, and also many testers and the main userbase is there.

**Comment by secsome** [comment]
@Metadorius I've never used it before... just let me install it. My username should be the same.

**Comment by secsome** [comment]
> @Metadorius I've never used it before... just let me install it. My username should be the same.

secsome#5043, that's it

**Comment by Metadorius** [comment]
There's couple of stuff that needs to be fixed regarding `CSFText` (serialization and deserialization is broken ATM) but since I can't push for some reason I'm merging this and fixing in `develop`.

**Pull request merged**
