### PR TITLE
Infantry DeployFireWeapon change

### LINKED ISSUE #25: Allow deployable infantry to fire both weapons when deployed
As of now, infantry units with Deployer=yes will use their Primary weapon when mobile and Secondary weapon when deployed. I propose to introduce a flag (i.e. DeployFireAll) that would allow them to use both Primary and Secondary weapons when deployed.

### PR DESCRIPTION
**Pull request by Thrifinesma**
Make infantry able to fire both weapons when deployed
closes #25

### CODE REVIEW

**Review by Metadorius — APPROVED** [review]

**Comment by Metadorius** [comment]
Need to resolve conflicts and add missing doc entries (what's new and readme.)

**Comment by SMxReaver** [comment]
infantrytest2

In testing, I used this GI lookalike with a deploying gimmick. I set the primary weapon to target only infantry and the secondary to target non infantry (via WH verses%). The unit becomes able to fire both weapons when deployed as shown in the gif, but can now fire both weapons while remaining standing and mobile as long as DeployFireWeapon=-1. Without DeployFireWeapon=-1, the primary weapon can only be fired while standing and mobile while firing the secondary can only be done while deployed and stationary.

**Comment by Metadorius** [comment]
To whoever first gets to this PR - update and merge it.

**Comment by Metadorius** [comment]
Erm, still not merged? I see localization conflicts also... @Thrifinesma I guess?

**Pull request merged**
