### PR TITLE
Adding Rad Site Stuffs

### PR DESCRIPTION
**Pull request by Otamaa**
In rulesmd.ini:
```INI
[SomeRadType]                  ; RadType
RadDurationMultiple=1          ; int
RadApplicationDelay=16         ; int
RadApplicationDelay.Building=0 ; int
RadLevelMax=500                ; int
RadLevelDelay=90               ; int
RadLightDelay=90               ; int
RadLevelFactor=0.2             ; int
RadLightFactor=0.1             ; int
RadTintFactor=1.0              ; int
RadColor=0,255,0               ; RGB
RadSiteWarhead=RadSite         ; WarheadType

[SomeWeapon]
RadLevel=100                   ; int, example
RadType=SomeRadType            ; RadType, default "Radiation"
```

### CODE REVIEW

**Comment by Belonit** [comment]
Slightly updated the style of the code. For example, I reduced nesting for for-if-else, and also managed to compress some hooks using DEFINE_HOOK_AGAIN and R->Origin()

**Comment by Otamaa** [comment]
oh , so thats how to use  return R->Origin() + X ; 
Thanks belonit

**Comment by Belonit** [comment]
@Otamaa Are you on our Discord? I'd like to discuss a few things in real-time, and also many testers and the main userbase is there.

**Comment by Otamaa** [comment]
Already at discord @BoredEXE#7189 @Belonit

**Comment by Metadorius** [comment]
Draft PR means that it's not ready to merge yet. Gluk is working on save/load code at the moment.

**Pull request merged**
