### PR TITLE
[Minor] Clear jumpjets' redundant destination

### PR DESCRIPTION
**Pull request by CrimRecya**
Clear jumpjets' redundant `Destination` when they change state to hovering.
This is for improving `align jumpjet turret's facing with body's`, and adapt to  #1308 .

### CODE REVIEW

**Review by chaserli — COMMENTED** [review]
I'm not sure about this, force queuing guard mission without target check seems a bit radical and I already observed something a bit weird.
That comment of mine was made 2+ years ago and I somehow doubt it now, I may need some explanation/confirmation.

**Comment by CrimRecya** [comment]
> I'm not sure about this, force queuing guard mission without target check seems a bit radical and I already observed something a bit weird. That comment of mine was made 2+ years ago and I somehow doubt it now, I may need some explanation/confirmation.

I have removed unnecessary queue guard mission. Everything I have done here is just to clear the jumpjet's `Destination` when it has arrived at its destination, just like others.

**Comment by Metadorius** [comment]
Why was the PR closed?

**Comment by CrimRecya** [comment]
> Why was the PR closed?

Oh, actually, I just learned about a phenomenon about some jumpjets that cannot attack while moving will get stuck in the move mission without destination and allow enemies to pass underneath them. I haven't thought of any good solutions yet.

**Pull request closed without merging**
