### PR TITLE
Append Ares' SW.Shots usage to sw tooltip

### PR DESCRIPTION
**Pull request by chaserli**
uimd.ini`[ToolTips]->SWShotsFormat` csf entry default to `Shots : %d`

### CODE REVIEW

**Comment by Metadorius** [comment]
Can you show a pic?

**Comment by chaserli** [comment]
> Can you show a pic how it looks right now with default settings?

image

**Comment by Metadorius** [comment]
Hmm what if we wrote `Name (7/10)` instead? seems intuitive enough and not overloaded much to me

**Comment by chaserli** [comment]
> Hmm what if we wrote `Name (7/10)` instead? seems intuitive enough and not overloaded much to me

Then you can simply overwrite it in csf. You can use only 1 number if you want.
The c-style parsing as well as the default str was suggested by others.
I understand what you were thinking. You have a better word for it?

**Pull request merged**
