### PR TITLE
Artillery projectile trajectory

### PR DESCRIPTION
**Pull request by FS-21**
- High altitude projctile capable to hit targets in high places.
- Height determined by `Trajectory.Artillery.MaxHeight`.
- Supported `Inaccurate=yes` and Ares costumization tags `BallisticScatter.Max` and `BallisticScatter.Min`.

In `rulesmd.ini`:
```ini
[SOMEPROJECTILE]                     ; Projectile
Trajectory=Artillery                 ; Trajectory type
Trajectory.Artillery.MaxHeight=2000  ; integer
```

Note: Re-used some code for Inaccurate projectiles from "arcing-fix" Phobos PR.

### CODE REVIEW

**Comment by NetsuNegi** [comment]
VYZ}E_1O8ID2 @JLBHDB}E8

The impact point of bullet maybe have some problem, I don't know if it is caused by the vanilla game.

**Comment by NetsuNegi** [comment]
The trail when bullet has been created is same as Trajectory=Straight, I think you should also adjust the Z velocity at the time of unlimbo.
The faster Trajectory.Speed means the more serious situation.

**Comment by MortonPL** [comment]
What's the difference between this and `Lobber=yes` on a weapon?

**Comment by Metadorius** [comment]
Eh more so, I would say maybe there's more point in continuing the arcing fix?

**Comment by FS-21** [comment]
> What's the difference between this and `Lobber=yes` on a weapon?

Can you set a projectile height with lobber=yes? No... 
I still need to fix some cases  but I'm busy with another PR.

**Comment by FS-21** [comment]
I want to remake it from scratch with a different approach so I close it and reopen it when I have free time for this idea.

**Pull request closed without merging**
