### PR TITLE
DropPod properties per InfantryType

### PR DESCRIPTION
**Pull request by chaserli**
```ini
[SOMEINFANTRY]
DropPod.Angle =            ; double, default to [General]->DropPodAngle, measured in radians
DropPod.AtmosphereEntry =  ; anim, default to [AudioVisual]->AtmosphereEntry
DropPod.GroundAnim =       ; 2 anims, default to [General]->DropPod
DropPod.AirImage =         ; SHP file, default to POD
DropPod.Height =           ; int, default to [General]->DropPodHeight
DropPod.Puff =             ; anim, default to [General]->DropPodPuff
DropPod.Speed =            ; int, default to [General]->DropPodSpeed
DropPod.Trailer =          ; anim, default to [General]->DropPodTrailer, which by default is SMOKEY , spawned every 6 frame
DropPod.Weapon =           ; weapon, default to [General]->DropPodWeapon
```

## Summary by CodeRabbit

- **New Features**
	- Introduced customizable DropPod properties for enhanced flexibility and customization, allowing different behaviors on a per-InfantryType basis.
	- Added new functionalities for managing DropPod types, including trailer animations, LaserTrails, weapon firing upon landing, and variable landing speeds.
- **Documentation**
	- Updated documentation to include details on the customization options available for DropPod properties.
- **Refactor**
	- Streamlined code by consolidating method calls into a single `OnEarlyUpdate()` method, improving code readability and maintainability.
- **Chores**
	- Added necessary files and classes to support the new DropPod customization features.

### CODE REVIEW

**Review by Starkku — CHANGES_REQUESTED** [review]
Code-wise looks mostly fine, `DroppodOnly` on laser trails is not documented though.

**Comment by Metadorius** [comment]
> Code-wise looks mostly fine, `DroppodOnly` on laser trails is not documented though.

bit off-topic (didn't look into PR, judging just from the comment) but maybe it would be better to make LaserTrails be able to be attached to some loco in general?

**Comment by chaserli** [comment]
> Code-wise looks mostly fine, `DroppodOnly` on laser trails is not documented though.

A few concerns:
* Anyone would actually use lasertrail on droppod? Is this implementation good?
* For the default value of trailer anim and image in air, is this parsing method correct?
* The trailer anim is detached from the body, the weapon just delivers warhead detonation, does this look good?

**Comment by Metadorius** [comment]
> * Anyone would actually use lasertrail on droppod? Is this implementation good?

I can't recall if we have an ext for base locomotionclass, if not - it would be good to have it and have lasertrails there. Then any locomotor could have it's own trails (processed in base loco class). INI-wise we would just declare trails per locomotor, so IMO the current impl. you proposed is a bit hacky/unsound.

And I think the usecase is there for this kind of functionality. Teleport loco could use one too for when the harvester is teleporting.

**Pull request merged**
