### PR TITLE
New Action 112 - Regroup around the Team Leader

### PR DESCRIPTION
**Pull request by FS-21**
Script action 74,n puts the TaskForce into Area Guard Mode for the given units of time around the Team Leader (this unit remains almost immobile until the action ends). 
The default guard area radius around the Leader is `[General] > CloseEnough` and the units will not leave that area. 
The countdown only works while all the units are inside the area.

Already tested inside PR 296 but I created it as a separate PR

### CODE REVIEW

**Comment by FS-21** [comment]
Now the countdown for jumping to the next action will start from the beginning to prevent infinite loops etc.

The only exception is argument 0 that remains without counter & launch the next action as soon as all the alive team members are gathered around the Leader.

**Review by Metadorius — CHANGES_REQUESTED** [review]
Same deal as with other PRs, need to review the code style (newlines, braces) and add changelog entry.

**Comment by FS-21** [comment]
I updated the code style with the previous feedback, if there is a mistake please notify me & I'll fix it.

**Review by FS-21 — COMMENTED** [review]
I think I finished with the changes

**Review by FS-21 — COMMENTED** [review]
done?

**Review by Metadorius — APPROVED** [review]

**Pull request merged**
