### PR TITLE
Remove the limitation of Waypoint

### PR DESCRIPTION
**Pull request by secsome**
In vanilla YR, this number is limited to [0, 701], this PR will remove that limitation.

~~Who will use all 702 waypoints?~~

### CODE REVIEW

**Comment by secsome** [comment]
For the map editor, see https://github.com/secsome/FA2sp/tree/develop

**Comment by E1Elite** [comment]
It would be better to give the modders an option to use this feature or not. It could be with like UseUnlimitedWaypoints boolean flag in rules INI.

**Comment by Metadorius** [comment]
> It would be better to give the modders an option to use this feature or not. It could be with like UseUnlimitedWaypoints boolean flag in rules INI.

Could you explain why would modders need that?

**Comment by E1Elite** [comment]
Sample tested trigger actions, numbers - 7, 41, 42, 43, 48, 63, 80, 88, 99, 128.
TeamType field - Waypoint.
Script actions - most of those.
Event number 24 was tested for not crashing.
Player locations in multiplayer map.
HomeCell and AltHomeCell.

These were found to be working as expected.

**Pull request merged**
