### PR TITLE
[Minor] Fix allies hospitals can not work properly

### PR DESCRIPTION
**Pull request by CrimRecya**
As the title says.

### CODE REVIEW

**Comment by Starkku** [comment]
Mind elaborating what exactly is broken here that this is supposed to fix?

**Comment by CrimRecya** [comment]
> Mind elaborating what exactly is broken here that this is supposed to fix?
> 
> I know there's a bug where the hospital now requires credits to operate which I have already fixed properly (alongside Units.RepairRate not working for Hospitals when the other stuff did).

I found this problem in campaign, when infantry enter a hospital that is not owned by the player, they will not heal after coming out. Perhaps it's the issue you're referring to ?

**Comment by Starkku** [comment]
> I found this problem in campaign, when infantry enter a hospital that is not owned by the player, they will not heal after coming out. Perhaps it's the issue you're referring to ?

If you could test it with latest develop nightly build that would help

**Comment by CrimRecya** [comment]
> > I found this problem in campaign, when infantry enter a hospital that is not owned by the player, they will not heal after coming out. Perhaps it's the issue you're referring to ?
> 
> If you could test it with latest develop nightly build that would help

It works!

**Pull request closed without merging**
