### PR TITLE
Script actions 99-110

### PR DESCRIPTION
**Pull request by FS-21**
All the remaining from PR 296.

### CODE REVIEW

**Review by secsome — DISMISSED** [review]
Better than before, just merge it if all tests have been done, I will try to improve the style when I'm free I guess.

**Comment by SMxReaver** [comment]
Can say these updates function as they did before, and changes to action 103 seem to be working as intended now as well. Perhaps this is ready for merging?

**Comment by FS-21** [comment]
This PR can be reviewed again if necessary & if acepted then merge.

**Comment by FS-21** [comment]
> Can say these updates function as they did before, and changes to action 103 seem to be working now as well. Perhaps this is ready for merging?

Can you try again with the latest build? I made some changes regarding saving/loading the selected target because I noticed too much target selections by the team I a unreasonable short period of time in the debug output and that means too much loops searching targets in the map.

And I have a question for everyone,
The selected target should be against a specific unit or any unit of a specified type?
Currently the team scores a kill when the specific unit is killed by any team member but maybe is more efficient if the team scores ANY unit kill of the same type...
Of course I can create (and maybe I should create it but I have to choose a default behavior) a new action modifier for switching between both scoring behaviors, the "specific instance of an object" could fit better in Single player missions and the "Generic kill" can fit better in Multiplayer maps.

**Review by Metadorius — APPROVED** [review]

**Pull request merged**
