### PR TITLE
`DecreasingRadDamage` for radiation types to deal linear decreasing rad damage

### PR DESCRIPTION
**Pull request by zhztheplayer**
Add new option `DecreasingRadDamage` for radiation types.

If set to true, damage dealt by radiation will decrease over time within factor calculated by `RadTimeLeft / RadDuration`. In the most common case, turning the option on could make radiation damage more consistent with its visualization (say, while the rad color gets lighter, it deals lower damage as well).

### CODE REVIEW

**Comment by Starkku** [comment]
Radiation damage already decreases over time. Damage per radiation processing tick (interval of frames defined by `RadApplicationDelay`) is `RadLevelFactor` * current radiation level. Current radiation level is recalculated at intervals equal to `RadLevelDelay` and reduced by amount matching initial `RadLevel` / `RadLevelDelay`. Similarly the lighting is also recalculated at intervals matching `RadLightDelay` using current radiation level to adjust it (after it has been reduced on same frame, if the timers are in sync). If the timers use same interval (which they do in vanilla YR).

Because of that, it is unclear to me what this change is supposed to accomplish.

**Comment by zhztheplayer** [comment]
> Current radiation level is recalculated at intervals equal to RadLevelDelay and reduced by amount matching initial RadLevel / RadLevelDelay.

Is this recaculation conducted by RA2 or Phobos? 

It's weired that I have been experiencing constant radiation damange in Phobos for quite some time. Following is my INI conf:

```ini
[Radiation]
RadTintFactor = 1.0
RadDurationMultiple = 1
RadLightDelay = 90
RadApplicationDelay = 15
RadSiteWarhead = RadSite
RadColor = 0,255,0
RadApplicationDelay.Building = 0
RadLevelFactor = 1.000000
RadLightFactor = 0.1
RadLevelMax = 500
RadLevelDelay = 90

[RADTYPE_120mmxL]
RadLevelMax = 500
RadColor = 0,135,0
RadLevelDelay = 90
RadSiteWarhead = RadSite
RadTintFactor = 1.0
RadLevelFactor = 0.450000
RadLightDelay = 90
RadHasOwner = true
RadLightFactor = 0.1
RadDurationMultiple = 1
RadSiteWarhead.Detonate = false
RadHasInvoker = true
```

Then if I add a log in `RadSite/Hook.cpp` to display the radiation damage:

```cpp
if (pFoot->IsAlive || !pFoot->IsSinking)
{
if (!pRadExt->ApplyRadiationDamage(pFoot, damage, Game::F2I(orDistance)))
	break;
Debug::Log("Rad damage %d\n", damage);
}
```

The log will be like:

```
[Phobos] Rad damage 258
[Phobos] Rad damage 258
[Phobos] Rad damage 258
[Phobos] Rad damage 258
[Phobos] Rad damage 333
[Phobos] Rad damage 308
[Phobos] Rad damage 308
[Phobos] Rad damage 308
[Phobos] Rad damage 308
[Phobos] Rad damage 308
[Phobos] Rad damage 308
[Phobos] Rad damage 308
[Phobos] Rad damage 308
[Phobos] Rad damage 308
[Phobos] Rad damage 308
[Phobos] Rad damage 308
[Phobos] Rad damage 308
[Phobos] Rad damage 308
[Phobos] Rad damage 308
[Phobos] Rad damage 308
[Phobos] Rad damage 308
[Phobos] Rad damage 308
[Phobos] Rad damage 308
[Phobos] Rad damage 308
[Phobos] Rad damage 308
[Phobos] Rad damage 308
```

Until the radiation vanishes. Am I doing something wrong in INI?

**Comment by Starkku** [comment]
It could be that there is a bug introduced by Phobos or that I have misunderstood something myself. I will test & investigate myself and see.

**Comment by zhztheplayer** [comment]
Thank you. And I just did more tests which showed it's possibly Phobos's bug since in vanilla YR a desolator's radiation damage does seem to decrease which is however constant with Phobos enabled.

I opened the PR because I thought constant damage was to match vanilla YR's behavior. If it's not intended then we may need a bug-fix rather than a new toggle.

**Comment by zhztheplayer** [comment]
Additionally given that it's a bug, we may need to update this function to make it return the time-aware radiation level:

https://github.com/Phobos-developers/Phobos/blob/796d446ef7985cf2c0b3dc41950ea8e302d6698b/src/Ext/RadSite/Body.cpp#L134-L149

**Comment by Starkku** [comment]
I have pushed a fix for this bug in 602d6962871ffb3ca4f973e24173783c2e515597. `RadLevelDelay` will now once again be respected for damage decay.

Will close this PR for time being. If a need arises in future for another look at this then can re-open.

**Pull request closed without merging**
