### PR TITLE
New scripttypes actions 71 and 72

### PR DESCRIPTION
**Pull request by FS-21**
Action 200,n : timed Area Guard.
Unlike the orignal timed Guard script (5,n) that just stays in place doing a basic guard operation the "Area Guard" action fits much better for base defense operations:
- The team go against nearby invasors.
- Units protection operation friendly.

### CODE REVIEW

**Comment by secsome** [comment]
> Action 200,n : timed Area Guard.
> Unlike the orignal timed Guard script (5,n) that just stays in place doing a basic guard operation the "Area Guard" action fits much better for base defense operations:
> 
> * The team go against nearby invasors.
> * Units protection operation friendly.

I'll be happy to see you spliting the hook into several functions to make the feature tidy.
That's better for later improvements I think.

**Comment by FS-21** [comment]
ScriptExt class created and moved some code from the original hook into method of this class.

**Comment by Belonit** [comment]
I rebase this branch. If someone does not agrees and wants to return everything as it was, just execute in terminal
`git reset --hard 217861c7937b34e775b90926b4214c7c073d10ea
git push --force`

**Comment by FS-21** [comment]
New ScriptType Action 72. Try the load of units into the transport**s**.
Initial working implementation. Looks as "stable" as other "load into transport" scripts.

**Comment by FS-21** [comment]
Fixed a targeting bug for single player missions. The units try to attack the transport they will try to enter.

**Comment by FS-21** [comment]
Added documentation.

**Pull request merged**
