### PR TITLE
SHP unit TurretOffest

### PR DESCRIPTION
**Pull request by Super-StarX**
Important but lacking logic

### CODE REVIEW

**Comment by Super-StarX** [comment]
Z6P1QI18E)`O7~`DER N6LF

**Review by Metadorius — APPROVED** [review]
Added docs, LGTM, let's wait until someone confirms it's working as intended and merge.

**Comment by SCIPCION** [comment]
Offset works perfectly, but that is not considering IsTilter=no

https://github.com/Phobos-developers/Phobos/assets/12478138/2045bcae-b297-4ef6-9496-b9e0e0cd0949

**Comment by Super-StarX** [comment]
> Offset works perfectly, but that is not considering IsTilter=no
> 
>  Desktop.21-08-2023.15-36-46.mp4

It looks like a maglev turret XD
fixed

**Comment by SCIPCION** [comment]
it works perfectly, thank you <3

https://github.com/Phobos-developers/Phobos/assets/12478138/9747818f-1f3b-416f-85f7-169611f2a53a

**Pull request merged**
