### PR TITLE
Enable and custom select box

### PR DESCRIPTION
**Pull request by NetsuNegi**
Now you can use and custom a select box for infantry, vehicle and aircraft. Not support on buildings.

in rulesmd.ini
[AudioVisual]
UseSelectBrd=no   (boolean)
SelectBrd.SHP.Infantry=select.shp   (filename, *including*the .shp extension)
SelectBrd.PAL.Infantry=palette.pal   (filename, *including*the .pal extension)
SelectBrd.Frame.Infantry=0,0,0   (frame, green hp, yellow hp, red hp)
SelectBrd.DrawOffset.Infantry=0,0   (X, Y, positive value is right and down)
SelectBrd.SHP.Unit=select.shp   (filename, *including*the .shp extension)
SelectBrd.PAL.Unit=palette.pal   (filename, *including*the .pal extension)
SelectBrd.Frame.Unit=3,3,3   (frame, green hp, yellow hp, red hp)
SelectBrd.DrawOffset.Unit=0,0   (X, Y, positive value is right and down)
SelectBrd.DefaultTranslucentLevel=0
SelectBrd.DefaultShowEnemy=true

Remember not for buildings!!!
[SOMETECHNO]
UseCustomSelectBrd=   (boolean, override the UseSelectBrd)
SelectBrd.SHP=   (filename, *including*the .shp extension)
SelectBrd.PAL=   (filename, *including*the .pal extension)
SelectBrd.Frame=   (frame, green hp, yellow hp, red hp)
SelectBrd.DrawOffset=   (X, Y, positive value is right and down)
SelectBrd.TranslucentLevel=
SelectBrd.ShowEnemy=

You can also set it in ra2md.ini
[Phobos]
EnableSelectBrd=false   (boolean)

### CODE REVIEW

**Comment by NetsuNegi** [comment]
If you don't have select.shp, maybe you can got it from Tiberium Sun.

**Comment by NetsuNegi** [comment]
}P QP8O8N5LH20TNZ3$2UM2
Just like this

**Comment by NetsuNegi** [comment]
07Z169$_ ~TI5 UXESBL)P0
(23T(K1T(D6GR(FLHUHTW`G
Just like this.

**Comment by NetsuNegi** [comment]
It also have some issue, I will try to fix it.

**Comment by NetsuNegi** [comment]
F)GUURJ( YQY790OC2F{XX3
9TKG8D9((99}WMA1 Z_ J8
Infantry can now display the correct selection box.

**Comment by NetsuNegi** [comment]
M{%30Q}CJ BI(B0D3FPRD13
Now you can custom translucent to the select box and whether the enemy can see it

**Comment by Metadorius** [comment]
One of our testers is in process of testing this, I think something is wrong with palette. He specified a custom palette and suddenly his placement preview and HP bars changed color:
image
image
image

**Comment by NetsuNegi** [comment]
> He just placed from Tiberian Sun in YR folder. Actually I think the game just loaded it instead of the default one because of the name.`palette.pal`

The palette.pal from TS and YR isn't exactly the same?

**Comment by NetsuNegi** [comment]
> He just placed `palette.pal` from Tiberian Sun in YR folder. Actually I think the game just loaded it instead of the default one because of the name.

You sure he toke palette.pal from original TS, not from some mod of TS ?

**Comment by Metadorius** [comment]
I am not sure on the palette name, we will re-check and get back to you.

**Comment by IgortheBylarge** [comment]
Ok, i just finished testing and i guess everything is working fine: separate frames for infantry&units, translucent, SelectBrd.ShowEnemy etc.

**Comment by NetsuNegi** [comment]
Oh, I need to update these code

**Comment by NetsuNegi** [comment]
Oh no......I have no time to update this.

**Comment by Metadorius** [comment]
why did you close it? everything was working fine...

**Comment by NetsuNegi** [comment]
> why did you close it? everything was working fine...

I don't know how to fetch develop branch, I will open it after a while.

**Comment by Metadorius** [comment]
Are you working from console?
Try GitKraken, it has a nice intuitive GUI and also has Chinese localization. I also can walk you through if you could get on our chat in Discord, so we don't spam this pull request.

**Comment by NetsuNegi** [comment]
> Are you working from console? Try GitKraken, it has a nice intuitive GUI and also has Chinese localization. I also can walk you through if you could get on our chat in Discord, so we don't spam this pull request.

My discord account has been banned permanent while I finished register. I don't know why by it just did.

**Pull request closed without merging**
