### PR TITLE
Unlimited skirmish player colors

### PR DESCRIPTION
**Pull request by MortonPL**
### Unlimited skirmish colors

- It is now possible to have an unlimited number of skirmish/multiplayer player colors, as opposed to 8 in Yuri's Revenge and 16 with Ares.
- This feature must be enabled with `SkirmishUnlimitedColors=true` in `[General]` section of game rules.
- When enabled, the game will treat color indices passed from spawner as indices for `[Colors]` section entries.
  - In example, with original rules, index 6 will correspond to color `Orange=25,230,255`.

```{note}
This feature should only be used if you use a spawner/outside client (i.e. CNCNet client). Using it in the original YR launcher will produce undesireable effects.
```

```{warning}
Due to technical incompatibilities, enabling this feature disables [Ares' Customizable Dropdown Colors](https://ares-developers.github.io/Ares-docs/ui-features/customizabledropdowncolors.html).
```

In `rulesmd.ini`:
```ini
[General]
SkirmishUnlimitedColors=false	; boolean
```

### CODE REVIEW

**Comment by a851903106** [comment]
Nice new feature, it works well, but I have a perhaps trivial question.

Now that it uses the number sequence number of [color] directly, if say the parameter inside [color] changes, will it affect all the colors that follow.

Is it possible to find this number by specifying the name of the color, rather than filling in the number directly.

**Comment by MortonPL** [comment]
> Is it possible to find this number by specifying the name of the color, rather than filling in the number directly.

It's possible, I think, but it would require additionally modifying the spawner and client code to work on names.

**Comment by MortonPL** [comment]
image

@Starkku I 'm not sure when "[units] do not retint correctly" occurs, but I think fixed the first two problems. As for the last one, probably something else is at fault.

**Comment by LeBaitBuruh** [comment]
I don't seem understand but let me get this straight... So if I enabled SkirmishUnlimitedColors and disabling the ares feature called Customizable Dropdown Colors then how I add more colors without that feature?

**Comment by brsajo** [comment]
> I don't seem understand but let me get this straight... So if I enabled SkirmishUnlimitedColors and disabling the ares feature called Customizable Dropdown Colors then how I add more colors without that feature?

Ares Custom dropdown is for the vanilla YR menu. 
This feature is Intended for use with a custom launcher such as the CnCnet Client Mod Base, which bypasses that altogether.

**Comment by LeBaitBuruh** [comment]
> > I don't seem understand but let me get this straight... So if I enabled SkirmishUnlimitedColors and disabling the ares feature called Customizable Dropdown Colors then how I add more colors without that feature?
> 
> Ares Custom dropdown is for the vanilla YR menu. This feature is Intended for use with a custom launcher such as the CnCnet Client Mod Base, which bypasses that altogether.

So that means that i can't edit colors in uimd and rulesmo way?

**Comment by MortonPL** [comment]
> > > I don't seem understand but let me get this straight... So if I enabled SkirmishUnlimitedColors and disabling the ares feature called Customizable Dropdown Colors then how I add more colors without that feature?
> > 
> > 
> > Ares Custom dropdown is for the vanilla YR menu. This feature is Intended for use with a custom launcher such as the CnCnet Client Mod Base, which bypasses that altogether.
> 
> So that means that it can't edit colors in uimd and rules(xx) way?

Colors in `uimd.ini` will be ignored completely - color numbers passed from spawner will be used as direct `[Colors]` color indices.

In example, if you use a DTA-based CNCNet client (like MO, RotE, or Mod Base), these default colors in `Resources/GameOptions.ini`:

```ini
[MPColors]
Yellow=230,220,13,0
Red=255,25,25,1
Blue=34,107,212,2
Green=61,210,45,3
Orange=255,160,25,4
Light Blue=49,217,230,5
Purple=146,40,189,6
Pink=255,153,237,7
```

will correspond to these colors in `rulesmd.ini` (note that with these defaults you will have different colors shown in client and in game):

```
[Colors]
LightGold=25,255,255
Gold=43,239,255
LightGrey=0,0,240
Grey=0,0,131
Red=20,255,184
DarkRed=0,230,255
Orange=25,230,255
Magenta=221,102,255
Purple=201,201,189
```

instead of the first 8 colors listed [here](https://ares-developers.github.io/Ares-docs/ui-features/customizabledropdowncolors.html#default-dropdown-color-values).

**Review by Starkku — APPROVED** [review]
The tint issues that were specific to this feature seem to be fixed now.

**Comment by LeBaitBuruh** [comment]
> > > > I don't seem understand but let me get this straight... So if I enabled SkirmishUnlimitedColors and disabling the ares feature called Customizable Dropdown Colors then how I add more colors without that feature?
> > > 
> > > 
> > > Ares Custom dropdown is for the vanilla YR menu. This feature is Intended for use with a custom launcher such as the CnCnet Client Mod Base, which bypasses that altogether.
> > 
> > 
> > So that means that it can't edit colors in uimd and rules(xx) way?
> 
> Colors in `uimd.ini` will be ignored completely - color numbers passed from spawner will be used as direct `[Colors]` color indices.
> 
> In example, if you use a DTA-based CNCNet client (like MO, RotE, or Mod Base), these default colors in `Resources/GameOptions.ini`:
> 
> ```ini
> [MPColors]
> Yellow=230,220,13,0
> Red=255,25,25,1
> Blue=34,107,212,2
> Green=61,210,45,3
> Orange=255,160,25,4
> Light Blue=49,217,230,5
> Purple=146,40,189,6
> Pink=255,153,237,7
> ```
> 
> will correspond to these colors in `rulesmd.ini` (note that with these defaults you will have different colors shown in client and in game):
> 
> ```
> [Colors]
> LightGold=25,255,255
> Gold=43,239,255
> LightGrey=0,0,240
> Grey=0,0,131
> Red=20,255,184
> DarkRed=0,230,255
> Orange=25,230,255
> Magenta=221,102,255
> Purple=201,201,189
> ```
> 
> instead of the first 8 colors listed [here](https://ares-developers.github.io/Ares-docs/ui-features/customizabledropdowncolors.html#default-dropdown-color-values).

So if i like for example
[MPColors]
Teal=0,168,168,0

then the 'rulesmd.ini' it will count as game
[Colors]
Teal=128,255,128

so it means it must be the same name both [MPColors] and [Colors] in order to work?

**Comment by Starkku** [comment]
> What happens if the names in [MPColors] has spaces Like "Light Blue=49,217,230,5" ? in rulesmd.ini the [Colors] the "Light Blue" with space is a valid key?

Non-trailing whitespace is treated as normal character like any other by standard INI parsers.

**Comment by MortonPL** [comment]
> So if i like for example [MPColors] Teal=0,168,168,0
> 
> then the 'rulesmd.ini' it will count as game [Colors] Teal=128,255,128
> 
> so it means it must be the same name both [MPColors] and [Colors] in order to work?

No, the name is not important here at all. The fourth number in an [MPColors] entry - the color index - matters. 0 means the first color in [Colors], 1 means the second color and so on.

**Comment by LeBaitBuruh** [comment]
> > So if i like for example [MPColors] Teal=0,168,168,0
> > then the 'rulesmd.ini' it will count as game [Colors] Teal=128,255,128
> > so it means it must be the same name both [MPColors] and [Colors] in order to work?
> 
> No, the name is not important here at all. The fourth number in an [MPColors] entry - the color index - matters. 0 means the first color in [Colors], 1 means the second color and so on.

i tried to test it but sadly it doesn't work, but i don't know if there are needed to modified the client or somthing?

**Comment by MortonPL** [comment]
> > > So if i like for example [MPColors] Teal=0,168,168,0
> > > then the 'rulesmd.ini' it will count as game [Colors] Teal=128,255,128
> > > so it means it must be the same name both [MPColors] and [Colors] in order to work?
> > 
> > 
> > No, the name is not important here at all. The fourth number in an [MPColors] entry - the color index - matters. 0 means the first color in [Colors], 1 means the second color and so on.
> 
> i tried to test it but sadly it doesn't work, but i don't know if there are needed to modified the client or somthing?

What are you trying to do? How do you know it doesn't work? Can you show your INI edits?

**Pull request merged**
