### PR TITLE
New trajectory called FullLine

### PR DESCRIPTION
**Pull request by FS-21**
- Is a straight-shot trajectory that doesn't end in the target.
- The weapon tag `ProjectileRange` must be set.
- Initial speed is determined by weapon's `Trajectory.Speed`.

### CODE REVIEW

**Comment by FS-21** [comment]
Visual example:
FullLine Trajectory

**Comment by Metadorius** [comment]
What happens if the projectile goes out of physical map area?
Also `FullLine` doesn't sound intuitive? Maybe if the logic is similar to `Straight` then maybe make it a flag `Straight.PassThrough`?

**Comment by Starkku** [comment]
I added a version that is part of `Trajectory=Straight` in my PR (#671) as `Trajectory.Straight.PassThrough` (name pending feedback). Sorry if I am stepping on your toes :pray:. My version takes into accord some things I fixed in that PR like warhead detonation/target snapping, PreImpactAnim etc. Only thing that's not really fixable is that the trajectory is still susceptible to the initial velocity vector, meaning that the firing angle is still determined by the original target so firing on ground right next to it will make the projectile hit the ground and not fly off to infinity.

**Comment by FS-21** [comment]
Closing PR because #671 is more complete :-D

**Pull request closed without merging**
