### PR TITLE
Allow to only grant `SpyEffects.InfiltratorSuperWeapon` instead of launching directly on site

### PR DESCRIPTION
**Pull request by chaserli**
In `rulesmd.ini`:
```ini
[SOMEBUILDING]                                     ; BuildingType
SpyEffect.Custom=false                            ; boolean
SpyEffect.VictimSuperWeapon=                      ; SuperWeaponType
SpyEffect.InfiltratorSuperWeapon=                 ; SuperWeaponType

; Added by this PR
SpyEffect.VictimSuperWeapon.RealLaunch=false   ; boolean
SpyEffect.InfiltratorSuperWeapon.JustGrant=false  ; boolean
```

https://user-images.githubusercontent.com/9932846/209951713-7490a5c8-5565-45ec-92c6-a5dc03b13711.mp4

### CODE REVIEW

**Comment by brsajo** [comment]
Isn't this already possible with Ares `SpyEffect.SuperWeapon=`?

**Comment by chaserli** [comment]
> Isn't this already possible with Ares `SpyEffect.SuperWeapon=`?

Does Ares even have this tag?

**Comment by brsajo** [comment]
> 
image

https://ares-developers.github.io/Ares-docs/new/buildings/spyeffects.html

**Comment by chaserli** [comment]
> > 
> 
> image
> 
> https://ares-developers.github.io/Ares-docs/new/buildings/spyeffects.html

Oh shit I didn't know

**Comment by chaserli** [comment]
The existing `SpyEffect.VictimSuperWeapon` and `SpyEffect.InfiltratorSuperWeapon` are quite confusing as well

**Pull request closed without merging**
